version: "3"

volumes:
  pg-database:
    driver: local

services:
  ec-cube:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://dbuser:secret@postgres/eccubedb"
      DATABASE_SERVER_VERSION: 14
      DATABASE_CHARSET: "utf8"

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pg-database:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - /tmp/pg_log:/var/lib/postgresql/data/pg_log:rw
    networks:
      - backend
      - default-shared
    healthcheck:
      test: pg_isready -U dbuser
      interval: 3s
      timeout: 3s
      retries: 3
